# save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#242424"
foreground = "#dcddde"

[colors.cursor]
cursor = "#99bbdd"
text   = "#1c2619"

[colors.normal]
black   = "#202020"
red     = "#ff4444"
green   = "#6BAD23"
yellow  = "#EDB322"
blue    = "#88aacc"
magenta = "#d3869b"
cyan    = "#95a99f"
white   = "#635E5C"

[colors.bright]
black   = "#555555"
red     = "#ff4444"
green   = "#6BAD23"
yellow  = "#EDB322"
blue    = "#88aacc"
magenta = "#d3869b"
cyan    = "#95a99f"
white   = "#dcddde"


[cursor]
blink_interval = 450

[cursor.style]
blinking = "on"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
# ibm plex mono
family = "Liberation Mono"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "copySelection"
mouse = "Right"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
# args = ["--login"]
program = "/usr/bin/bash"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 0
y = 0

[general]
live_config_reload = true

[terminal]
